In [4]:
from __future__ import print_function
import torch as t

In [6]:
x = t.Tensor(5,3)
x

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [11]:
x = t.rand(5,3)
x

tensor([[0.7055, 0.6304, 0.9375],
        [0.3093, 0.7635, 0.8346],
        [0.6048, 0.0478, 0.5970],
        [0.6452, 0.0393, 0.1586],
        [0.4479, 0.3319, 0.0496]])

In [18]:
print(x.size())
x.size()[0], x.size(1) #是要印出 torch.Size([5,3]) 裡面的5 and 3

torch.Size([5, 3])


(5, 3)

In [24]:
y = t.rand(5,3)
x + y
print(x)
print(y)
print(x + y)

tensor([[0.7055, 0.6304, 0.9375],
        [0.3093, 0.7635, 0.8346],
        [0.6048, 0.0478, 0.5970],
        [0.6452, 0.0393, 0.1586],
        [0.4479, 0.3319, 0.0496]])
tensor([[0.1115, 0.7979, 0.7767],
        [0.4703, 0.4456, 0.0047],
        [0.5207, 0.2321, 0.7734],
        [0.5805, 0.4496, 0.8762],
        [0.3789, 0.9098, 0.5477]])
tensor([[0.8171, 1.4283, 1.7143],
        [0.7796, 1.2092, 0.8392],
        [1.1255, 0.2799, 1.3704],
        [1.2257, 0.4889, 1.0348],
        [0.8268, 1.2417, 0.5973]])


In [27]:
t.add(x, y)

tensor([[0.8171, 1.4283, 1.7143],
        [0.7796, 1.2092, 0.8392],
        [1.1255, 0.2799, 1.3704],
        [1.2257, 0.4889, 1.0348],
        [0.8268, 1.2417, 0.5973]])

In [32]:
result = t.Tensor(5,3)
t.add(x, y, out=result)
result

tensor([[0.8171, 1.4283, 1.7143],
        [0.7796, 1.2092, 0.8392],
        [1.1255, 0.2799, 1.3704],
        [1.2257, 0.4889, 1.0348],
        [0.8268, 1.2417, 0.5973]])